name: Issue Close Require

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  close-issues:
    runs-on: ubuntu-latest
    steps:
      - name: close issue
        uses: actions-cool/issues-helper@v3
        with:
          actions: close-issues
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: need more info
          inactive-day: 1
